### PR TITLE
Removal of redundant f64()

### PR DESCRIPTION
**Pull request by tuxiqae**

### CODE REVIEW

**Comment by tidwall** [comment]
Thanks for detecting the typo.
I think I meant that line to be `value.f32()` (followed by an `value.f64()` line).
If change it to that instead of deleting the line then I'll merge.

**Comment by tidwall** [comment]
I went ahead and changed f64() to f32(). Thanks for reporting.

**Comment by tuxiqae** [comment]
My bad, sorry :stuck_out_tongue:

**Comment by tidwall** [comment]
No worries :)

**Pull request closed without merging**
